-- Offline alembic upgrade: d4f1a8b62c70 -> 37d57cfdb27d
-- Generated 2026-05-24 from `alembic upgrade d4f1a8b62c70:37d57cfdb27d --sql`.
-- See docs/bugs/apple-health-prod-migration.md for context.
--
-- Apply with:
--   psql "$RAILWAY_URL" -f scripts/migrations/2026-05-24-apple-health-upgrade.sql
--
-- Before applying, verify prod is actually at d4f1a8b62c70:
--   psql "$RAILWAY_URL" -c "SELECT version_num FROM alembic_version;"
--   psql "$RAILWAY_URL" -c "\d activities"      -- should NOT contain `source`
--   psql "$RAILWAY_URL" -c "\dt user_profile"   -- should be empty / not exist
-- If columns or tables in this script already exist, do NOT run this file —
-- inspect the actual schema and apply only the missing pieces.

BEGIN;

-- Running upgrade d4f1a8b62c70 -> e8f31a902b94

CREATE TABLE user_profile (
    id SERIAL NOT NULL, 
    payload JSON NOT NULL, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id)
);

UPDATE alembic_version SET version_num='e8f31a902b94' WHERE alembic_version.version_num = 'd4f1a8b62c70';

-- Running upgrade e8f31a902b94 -> f9c2e1a45b80

CREATE TABLE oauth_tokens (
    provider VARCHAR(32) NOT NULL, 
    access_token TEXT, 
    refresh_token TEXT, 
    expires_at TIMESTAMP WITH TIME ZONE, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (provider)
);

UPDATE alembic_version SET version_num='f9c2e1a45b80' WHERE alembic_version.version_num = 'e8f31a902b94';

-- Running upgrade f9c2e1a45b80 -> a9d2f6c1e3b7

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'activities';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'activities';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'activities';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'activities';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'activities'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'activities', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'activity_laps';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'activity_laps';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activity_laps'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'activity_laps';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'activity_laps';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'activity_laps'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'activity_laps', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'activity_streams';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'activity_streams';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activity_streams'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'activity_streams';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'activity_streams';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'activity_streams'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'activity_streams', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'analysis_cache';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'analysis_cache';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'analysis_cache'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'analysis_cache';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'analysis_cache';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'analysis_cache'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'analysis_cache', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'goals';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'goals';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'goals'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'goals';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'goals';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'goals'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'goals', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'recommendation_feedback';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'recommendation_feedback';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'recommendation_feedback'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'recommendation_feedback';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'recommendation_feedback';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'recommendation_feedback'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'recommendation_feedback', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'recovery_metrics';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'recovery_metrics';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'recovery_metrics'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'recovery_metrics';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'recovery_metrics';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'recovery_metrics'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'recovery_metrics', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'sleep_sessions';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'sleep_sessions';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sleep_sessions'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'sleep_sessions';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'sleep_sessions';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'sleep_sessions'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'sleep_sessions', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'strength_sets';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'strength_sets';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'strength_sets'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'strength_sets';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'strength_sets';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'strength_sets'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'strength_sets', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'sync_log';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'sync_log';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sync_log'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'sync_log';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'sync_log';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'sync_log'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'sync_log', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'user_locations';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'user_locations';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'user_locations'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'user_locations';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'user_locations';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'user_locations'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'user_locations', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'user_profile';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'user_profile';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'user_profile'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'user_profile';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'user_profile';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'user_profile'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'user_profile', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'weather_snapshots';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'weather_snapshots';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'weather_snapshots'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'weather_snapshots';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'weather_snapshots';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'weather_snapshots'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'weather_snapshots', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', 'whoop_workouts';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', 'whoop_workouts';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', 'whoop_workouts';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                'whoop_workouts'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                'whoop_workouts', start_val
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'start_date';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'start_date';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'start_date';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'start_date', 'start_date'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'start_date_local';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'start_date_local';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'start_date_local';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'start_date_local', 'start_date_local'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'enriched_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'enriched_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'enriched_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'enriched_at', 'enriched_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'classified_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'classified_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'classified_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'classified_at', 'classified_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'rated_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'rated_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'rated_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'rated_at', 'rated_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activities'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activities', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activities', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activities', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'activity_laps'
              AND column_name = 'start_date';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'activity_laps', 'start_date';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'activity_laps', 'start_date';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'activity_laps', 'start_date', 'start_date'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'analysis_cache'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'analysis_cache', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'analysis_cache', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'analysis_cache', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'analysis_cache'
              AND column_name = 'expires_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'analysis_cache', 'expires_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'analysis_cache', 'expires_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'analysis_cache', 'expires_at', 'expires_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'goals'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'goals', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'goals', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'goals', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'goals'
              AND column_name = 'updated_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'goals', 'updated_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'goals', 'updated_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'goals', 'updated_at', 'updated_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'recommendation_feedback'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'recommendation_feedback', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'recommendation_feedback', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'recommendation_feedback', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'recovery_metrics'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'recovery_metrics', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'recovery_metrics', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'recovery_metrics', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sleep_sessions'
              AND column_name = 'bed_time';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'sleep_sessions', 'bed_time';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'sleep_sessions', 'bed_time';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'sleep_sessions', 'bed_time', 'bed_time'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sleep_sessions'
              AND column_name = 'wake_time';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'sleep_sessions', 'wake_time';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'sleep_sessions', 'wake_time';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'sleep_sessions', 'wake_time', 'wake_time'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sleep_sessions'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'sleep_sessions', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'sleep_sessions', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'sleep_sessions', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'strength_sets'
              AND column_name = 'performed_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'strength_sets', 'performed_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'strength_sets', 'performed_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'strength_sets', 'performed_at', 'performed_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'strength_sets'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'strength_sets', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'strength_sets', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'strength_sets', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'strength_sets'
              AND column_name = 'updated_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'strength_sets', 'updated_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'strength_sets', 'updated_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'strength_sets', 'updated_at', 'updated_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sync_log'
              AND column_name = 'started_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'sync_log', 'started_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'sync_log', 'started_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'sync_log', 'started_at', 'started_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'sync_log'
              AND column_name = 'completed_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'sync_log', 'completed_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'sync_log', 'completed_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'sync_log', 'completed_at', 'completed_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'user_locations'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'user_locations', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'user_locations', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'user_locations', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'user_profile'
              AND column_name = 'updated_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'user_profile', 'updated_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'user_profile', 'updated_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'user_profile', 'updated_at', 'updated_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'weather_snapshots'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'weather_snapshots', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'weather_snapshots', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'weather_snapshots', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts'
              AND column_name = 'start';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'whoop_workouts', 'start';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'whoop_workouts', 'start';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'whoop_workouts', 'start', 'start'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts'
              AND column_name = 'end';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'whoop_workouts', 'end';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'whoop_workouts', 'end';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'whoop_workouts', 'end', 'end'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts'
              AND column_name = 'created_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'whoop_workouts', 'created_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'whoop_workouts', 'created_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'whoop_workouts', 'created_at', 'created_at'
            );
        END
        $$;;

DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'whoop_workouts'
              AND column_name = 'updated_at';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', 'whoop_workouts', 'updated_at';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', 'whoop_workouts', 'updated_at';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                'whoop_workouts', 'updated_at', 'updated_at'
            );
        END
        $$;;

UPDATE alembic_version SET version_num='a9d2f6c1e3b7' WHERE alembic_version.version_num = 'f9c2e1a45b80';

-- Running upgrade a9d2f6c1e3b7 -> 37d57cfdb27d

CREATE TABLE health_data_points (
    id SERIAL NOT NULL, 
    source VARCHAR(32) NOT NULL, 
    data_type VARCHAR(32) NOT NULL, 
    external_id VARCHAR(128) NOT NULL, 
    start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
    end_time TIMESTAMP WITH TIME ZONE, 
    superseded_by_id INTEGER, 
    raw_payload JSON, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(superseded_by_id) REFERENCES health_data_points (id) ON DELETE SET NULL, 
    CONSTRAINT uq_health_data_points_source_type_ext UNIQUE (source, data_type, external_id)
);

CREATE INDEX ix_health_data_points_source ON health_data_points (source);

CREATE INDEX ix_health_data_points_data_type ON health_data_points (data_type);

CREATE INDEX ix_health_data_points_start_time ON health_data_points (start_time);

CREATE INDEX ix_health_data_points_superseded_by_id ON health_data_points (superseded_by_id);

CREATE INDEX ix_health_data_points_data_type_start_time ON health_data_points (data_type, start_time);

CREATE TABLE workouts (
    id INTEGER NOT NULL, 
    activity_type VARCHAR(48) NOT NULL, 
    duration_s INTEGER, 
    active_energy_kcal FLOAT, 
    distance_m FLOAT, 
    avg_speed_mps FLOAT, 
    avg_pace_s_per_km FLOAT, 
    avg_hr FLOAT, 
    max_hr FLOAT, 
    total_elevation_m FLOAT, 
    activity_id INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(id) REFERENCES health_data_points (id) ON DELETE CASCADE, 
    FOREIGN KEY(activity_id) REFERENCES activities (id) ON DELETE SET NULL
);

CREATE INDEX ix_workouts_activity_type ON workouts (activity_type);

CREATE INDEX ix_workouts_activity_id ON workouts (activity_id);

CREATE TABLE workout_laps (
    id SERIAL NOT NULL, 
    workout_id INTEGER NOT NULL, 
    lap_index INTEGER NOT NULL, 
    name VARCHAR, 
    elapsed_time_s INTEGER, 
    moving_time_s INTEGER, 
    distance_m FLOAT, 
    start_time TIMESTAMP WITH TIME ZONE, 
    avg_speed_mps FLOAT, 
    max_speed_mps FLOAT, 
    avg_hr FLOAT, 
    max_hr FLOAT, 
    avg_cadence FLOAT, 
    total_elevation_m FLOAT, 
    split INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(workout_id) REFERENCES workouts (id) ON DELETE CASCADE, 
    CONSTRAINT uq_workout_laps_workout_lap_index UNIQUE (workout_id, lap_index)
);

CREATE INDEX ix_workout_laps_workout_id ON workout_laps (workout_id);

ALTER TABLE activities ADD COLUMN source VARCHAR(32);

ALTER TABLE activities ADD COLUMN external_id VARCHAR(128);

ALTER TABLE activities ADD COLUMN superseded_by_id INTEGER;

CREATE INDEX ix_activities_superseded_by_id ON activities (superseded_by_id);

UPDATE activities SET source = 'strava' WHERE source IS NULL;

UPDATE activities SET external_id = CAST(strava_id AS TEXT) WHERE external_id IS NULL;

UPDATE alembic_version SET version_num='37d57cfdb27d' WHERE alembic_version.version_num = 'a9d2f6c1e3b7';

COMMIT;

