"""Persist live Railway fixes: id IDENTITY + timezone-aware datetimes.

Revision ID: a9d2f6c1e3b7
Revises: f9c2e1a45b80
Create Date: 2026-05-24

Background
----------
Two SQLite → Postgres migration regressions were patched live against
the Railway database during the audit-001 mission and never landed in
the migration history:

1. **No autoincrement on ``id`` columns.** SQLite implicitly
   auto-increments ``INTEGER PRIMARY KEY``; Postgres does not. The
   ``create_all``-generated schema on Railway had 14 tables with
   ``id bigint NOT NULL`` and no DEFAULT or IDENTITY, so every INSERT
   that didn't supply ``id`` manually failed with
   ``NotNullViolationError``. Live fix: ``scripts/fix_id_autoincrement.py``
   added ``GENERATED BY DEFAULT AS IDENTITY`` to each affected table.

2. **DateTime columns declared without ``timezone=True``.** The Railway
   columns are ``TIMESTAMP WITH TIME ZONE`` but the SQLAlchemy models
   declared them as bare ``DateTime``, causing asyncpg to refuse to
   bind tz-aware Python datetimes. Live fix on ``main`` (commits
   ``e87220f``, ``35d648f``) added ``timezone=True`` to every affected
   column declaration.

Both fixes work against the current Railway DB but exist nowhere in
the migration history. A fresh deploy or a Postgres restore would
regress. This migration locks both in.

The migration is **Postgres-only DDL** — IDENTITY syntax and ``ALTER
COLUMN ... TYPE timestamptz USING ... AT TIME ZONE 'UTC'`` are both
Postgres features. On SQLite the upgrade/downgrade are no-ops (the
column types are already correct on a fresh SQLite ``create_all`` and
SQLite's ROWID auto-increment is already in place). Both branches are
idempotent: re-running the upgrade is safe.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9d2f6c1e3b7"
down_revision: Union[str, None] = "f9c2e1a45b80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 14 tables that `scripts/fix_id_autoincrement.py --apply` patched on
# Railway. ``goals`` and ``recovery_metrics`` are the canonical DB
# names; a separate concurrent task (A2) reconciles the few code
# call-sites that still reference ``goal`` / ``recovery_records``.
IDENTITY_TABLES: tuple[str, ...] = (
    "activities",
    "activity_laps",
    "activity_streams",
    "analysis_cache",
    "goals",
    "recommendation_feedback",
    "recovery_metrics",
    "sleep_sessions",
    "strength_sets",
    "sync_log",
    "user_locations",
    "user_profile",
    "weather_snapshots",
    "whoop_workouts",
)


# Map of table -> list of DateTime columns that should be TIMESTAMP
# WITH TIME ZONE. Enumerated from `grep -rn 'DateTime(timezone=True)'
# backend/models/` (excluding ``oauth_tokens`` which was created with
# timezone=True from the start, per commit f9c2e1a45b80).
TIMEZONE_COLUMNS: dict[str, tuple[str, ...]] = {
    "activities": (
        "start_date",
        "start_date_local",
        "enriched_at",
        "classified_at",
        "rated_at",
        "created_at",
    ),
    "activity_laps": ("start_date",),
    "analysis_cache": ("created_at", "expires_at"),
    "goals": ("created_at", "updated_at"),
    "recommendation_feedback": ("created_at",),
    "recovery_metrics": ("created_at",),
    "sleep_sessions": ("bed_time", "wake_time", "created_at"),
    "strength_sets": ("performed_at", "created_at", "updated_at"),
    "sync_log": ("started_at", "completed_at"),
    "user_locations": ("created_at",),
    "user_profile": ("updated_at",),
    "weather_snapshots": ("created_at",),
    "whoop_workouts": ("start", "end", "created_at", "updated_at"),
}


def _is_postgres() -> bool:
    bind = op.get_bind()
    return bind.dialect.name == "postgresql"


def _add_identity(table: str) -> None:
    """Idempotently add ``GENERATED BY DEFAULT AS IDENTITY`` to ``id``.

    Skips the ALTER if the column is already IDENTITY or already has a
    DEFAULT (e.g. a serial sequence from a different code path). The
    starting value is computed at migration time from ``MAX(id)+1`` so
    existing rows aren't disturbed; for an empty table the sequence
    starts at 1.
    """
    op.execute(
        f"""
        DO $$
        DECLARE
            has_identity text;
            has_default text;
            tbl_exists int;
            start_val bigint;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = '{table}';
            IF tbl_exists = 0 THEN
                RAISE NOTICE 'skip identity: table % missing', '{table}';
                RETURN;
            END IF;

            SELECT is_identity, column_default
              INTO has_identity, has_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = '{table}'
              AND column_name = 'id';

            IF has_identity IS NULL THEN
                RAISE NOTICE 'skip identity: column id missing on %', '{table}';
                RETURN;
            END IF;

            IF has_identity = 'YES' OR has_default IS NOT NULL THEN
                RAISE NOTICE 'skip identity: % already auto-incrementing', '{table}';
                RETURN;
            END IF;

            EXECUTE format(
                'SELECT COALESCE(MAX(id), 0) + 1 FROM %I',
                '{table}'
            ) INTO start_val;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                '{table}', start_val
            );
        END
        $$;
        """
    )


def _drop_identity(table: str) -> None:
    """Idempotently drop IDENTITY from ``id``.

    Uses ``DROP IDENTITY IF EXISTS`` (Postgres 10+). Safe to run when
    the column is not an identity column or the table is missing.
    """
    op.execute(
        f"""
        DO $$
        DECLARE
            tbl_exists int;
        BEGIN
            SELECT count(*) INTO tbl_exists
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = '{table}';
            IF tbl_exists = 0 THEN
                RETURN;
            END IF;
            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN id DROP IDENTITY IF EXISTS',
                '{table}'
            );
        END
        $$;
        """
    )


def _convert_to_timestamptz(table: str, column: str) -> None:
    """Idempotently convert a column to ``TIMESTAMP WITH TIME ZONE``.

    Skips if already ``timestamp with time zone`` or if the table /
    column is missing. The ``USING ... AT TIME ZONE 'UTC'`` clause
    treats any existing naive timestamps as UTC, matching what the
    application code has been writing.
    """
    op.execute(
        f"""
        DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = '{table}'
              AND column_name = '{column}';

            IF current_type IS NULL THEN
                RAISE NOTICE 'skip tz convert: % . % missing', '{table}', '{column}';
                RETURN;
            END IF;

            IF current_type = 'timestamp with time zone' THEN
                RAISE NOTICE 'skip tz convert: % . % already tz-aware', '{table}', '{column}';
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITH TIME ZONE USING %I AT TIME ZONE ''UTC''',
                '{table}', '{column}', '{column}'
            );
        END
        $$;
        """
    )


def _convert_to_timestamp_naive(table: str, column: str) -> None:
    """Idempotent inverse: convert ``timestamptz`` back to naive.

    Uses ``AT TIME ZONE 'UTC'`` to flatten the tz, matching the
    pre-fix state.
    """
    op.execute(
        f"""
        DO $$
        DECLARE
            current_type text;
        BEGIN
            SELECT data_type INTO current_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = '{table}'
              AND column_name = '{column}';

            IF current_type IS NULL THEN
                RETURN;
            END IF;

            IF current_type = 'timestamp without time zone' THEN
                RETURN;
            END IF;

            EXECUTE format(
                'ALTER TABLE %I ALTER COLUMN %I TYPE TIMESTAMP WITHOUT TIME ZONE USING %I AT TIME ZONE ''UTC''',
                '{table}', '{column}', '{column}'
            );
        END
        $$;
        """
    )


def upgrade() -> None:
    if not _is_postgres():
        # SQLite ROWID handles auto-increment; SQLite has no separate
        # timestamptz type. Nothing to do.
        return

    for table in IDENTITY_TABLES:
        _add_identity(table)

    for table, columns in TIMEZONE_COLUMNS.items():
        for column in columns:
            _convert_to_timestamptz(table, column)


def downgrade() -> None:
    if not _is_postgres():
        return

    for table, columns in TIMEZONE_COLUMNS.items():
        for column in columns:
            _convert_to_timestamp_naive(table, column)

    for table in IDENTITY_TABLES:
        _drop_identity(table)
