"""Add IDENTITY to id columns that are missing it on Railway Postgres.

Background: the v1 → Railway migration didn't preserve SQLite's
implicit ROWID auto-increment. Tables ended up with `id bigint NOT
NULL` and no DEFAULT / IDENTITY metadata, so every INSERT that
doesn't supply id manually fails with NotNullViolationError. This
blocked both Bug A (sync_log inserts → scheduler dead) and Bug B
(strength_sets inserts → lifting save 500s).

This script ALTERs every affected table to add IDENTITY on id, with
the sequence starting at MAX(id) + 1 so existing rows aren't disturbed.

Usage:

    # Dry-run — prints the plan only, makes no changes.
    DATABASE_URL='postgresql://...' python scripts/fix_id_autoincrement.py

    # Apply for real.
    DATABASE_URL='postgresql://...' python scripts/fix_id_autoincrement.py --apply

Take a Railway Postgres snapshot from the dashboard before running
with --apply. The script wraps everything in a single transaction
(ROLLBACK on any error), but a snapshot is the easy escape hatch
if anything unexpected happens.
"""
from __future__ import annotations

import asyncio
import os
import sys

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection, create_async_engine


def _async_db_url() -> str:
    url = os.environ.get("DATABASE_URL") or os.environ.get("DATABASE_PUBLIC_URL")
    if not url:
        sys.exit("DATABASE_URL is not set.")
    if url.startswith("postgresql://"):
        return url.replace("postgresql://", "postgresql+asyncpg://", 1)
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+asyncpg://", 1)
    return url


async def _broken_tables(conn: AsyncConnection) -> list[str]:
    rows = (
        await conn.execute(
            text(
                """
                SELECT table_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND column_name = 'id'
                  AND column_default IS NULL
                  AND is_identity = 'NO'
                ORDER BY table_name
                """
            )
        )
    ).mappings().all()
    return [row["table_name"] for row in rows]


async def _max_id(conn: AsyncConnection, table: str) -> int:
    # COALESCE handles empty tables — start the sequence at 1.
    result = await conn.execute(
        text(f'SELECT COALESCE(MAX(id), 0) AS m FROM "{table}"')
    )
    row = result.mappings().one()
    return int(row["m"])


async def _apply_identity(conn: AsyncConnection, table: str, start: int) -> None:
    # ALTER TABLE ... ADD GENERATED BY DEFAULT AS IDENTITY requires
    # Postgres 10+. The (START WITH N) clause sets the next-value
    # cursor; the internal sequence is created automatically.
    await conn.execute(
        text(
            f'ALTER TABLE "{table}" '
            f'ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY '
            f'(START WITH {start})'
        )
    )


async def _verify(conn: AsyncConnection, table: str) -> bool:
    row = (
        await conn.execute(
            text(
                """
                SELECT is_identity, column_default
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = :t
                  AND column_name = 'id'
                """
            ),
            {"t": table},
        )
    ).mappings().one_or_none()
    if not row:
        return False
    return row["is_identity"] == "YES"


async def main() -> int:
    apply = "--apply" in sys.argv[1:]
    url = _async_db_url()
    if not url.startswith("postgresql"):
        sys.exit("This script targets Postgres.")

    print(f"Mode: {'APPLY (changes will be made)' if apply else 'DRY RUN (no changes)'}")
    print()

    engine = create_async_engine(url, echo=False)
    try:
        async with engine.connect() as conn:
            tables = await _broken_tables(conn)
            if not tables:
                print("No broken id columns found. Nothing to do.")
                return 0
            print(f"Found {len(tables)} table(s) with no autoincrement on id:")
            print()
            plan = []
            for table in tables:
                max_id = await _max_id(conn, table)
                start = max_id + 1
                plan.append((table, max_id, start))
                print(
                    f"  - {table:<28} MAX(id)={max_id:<10} "
                    f"→ START WITH {start}"
                )
            print()

        if not apply:
            print("Dry run complete. Re-run with --apply to execute.")
            return 0

        # Real run — single transaction so all-or-nothing.
        async with engine.begin() as conn:
            for table, _max_id_val, start in plan:
                print(f"  applying: {table} (start={start}) ...", end=" ")
                await _apply_identity(conn, table, start)
                print("ok")
        print()
        print("Transaction committed. Verifying ...")
        print()

        # Verify in a fresh connection.
        async with engine.connect() as conn:
            all_ok = True
            for table, _, _ in plan:
                ok = await _verify(conn, table)
                mark = "OK" if ok else "FAIL"
                print(f"  - {mark}  {table}")
                if not ok:
                    all_ok = False
        if not all_ok:
            print()
            print("VERIFICATION FAILED for one or more tables. "
                  "Investigate before retrying.")
            return 2
        print()
        print("All affected tables now have IDENTITY on id. "
              "Re-run scripts/diagnose_railway.py to confirm.")
        return 0
    finally:
        await engine.dispose()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
